In [1]:
import numpy as np
import cv2 as cv

In [14]:
img = cv.imread('C:/Users/XOTOURLLIFE/Desktop/Jung/24-1/Computer_Vision/practice/peppers.tif')
assert img is not None, 'Cannot read the given image'

In [8]:
# img object의 shape 출력
print(img.shape)

(512, 512, 3)


In [27]:
img_hsv = cv.cvtColor(img, cv.COLOR_BGR2HSV)

In [29]:
# height, width, HSV(Hue, Saturation, Value Channels: 색상, 채도, 명도)
img_hsv.shape

(512, 512, 3)

In [31]:
height, width, channels = img_hsv.shape

for y in range(height):
    for x in range(width):
        img_hsv[:, :, 0] = 0

cv.imshow('Hue is 0', img_hsv)
cv.waitKey()
cv.destroyAllWindows()

KeyboardInterrupt: 

In [12]:
img_Rto0 = img

height, width, channels = img_Rto0.shape

#BGR중 R을 0으로 update
for y in range(height):
    for x in range(width):
        img_Rto0[y, x, 2] = 0

cv.imshow('Rto0', img_Rto0)
cv.waitKey()
cv.destroyAllWindows()

In [15]:
img_flip = img[::-1, :, :]
cv.imshow('flipped', img_flip)
cv.waitKey()
cv.destroyAllWindows()

In [18]:
img_flip = img[:,:,:]
cv.imshow('flipped', img_flip)
cv.waitKey()
cv.destroyAllWindows()

In [6]:
cv.imshow('test', img)
cv.waitKey()
cv.destroyAllWindows()

In [23]:
my_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
my_list = np.array(my_list)
my_list.shape

(2, 2, 2)

In [24]:
print(my_list)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
test_list = my_list[:, :, ::-1]
test_list

array([[[3, 4],
        [1, 2]],

       [[7, 8],
        [5, 6]]])